services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["7072:1972","5001:5000"]
    container_name: abiciris
    volumes: ["./data:/data","./src:/src"]
    environment: 
      - TZ=JST-9

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:2025.1
    container_name: abicWG
    init: true
    ports:
      - 7080:80
      - 7443:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared